# Generated by Django 5.0 on 2023-12-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='stringname',
            new_name='name_link',
        ),
    ]
